version: '3.8'
services:
  websiteffacb:
    container_name: FFACB
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik-net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.FFACB.rule=Host(`ffacb-beta.guillian.net`)'
      - 'traefik.http.routers.FFACB.entrypoints=http'
      - 'traefik.http.routers.FFACB-secure.rule=Host(`ffacb-beta.guillian.net`)'
      - 'traefik.http.routers.FFACB-secure.entrypoints=https'
      - 'traefik.http.routers.FFACB-secure.tls=false'
      - 'traefik.http.services.FFACB.loadbalancer.server.port=3000'
      - 'traefik.docker.network=traefik-net'
      - 'traefik.http.routers.FFACB-secure.middlewares=FFACB-redirect'
      - 'traefik.http.routers.FFACB.middlewares=FFACB-redirect'
      - 'traefik.http.middlewares.FFACB-redirect.redirectregex.regex=^https?://guillian\\.net/(.*)'
      - 'traefik.http.middlewares.FFACB-redirect.redirectregex.replacement=https://ffacb-beta.guillian.net/$${1}'
      - 'traefik.http.middlewares.FFACB-redirect.redirectregex.permanent=false'
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs
      - type: bind
        source: ./prisma/db
        target: /app/prisma/db
      - type: bind
        source: ./uploads/
        target: /app/uploads/
networks:
  traefik-net:
    external: true
